### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by 4ortytwo** [11bit/jotai-minidb#2]
Hey there! Such an awesome package. I'm going to be honest, I'm using it in production 😁 
Getting this error quite a lot, especially if a tab was left open for a while and a user returns to it. Mobile devices seem to be more susceptible to this issue. 

Was wondering if you've ever had this issue and whether there is a slight hope it's going to be maintained, though, I might be the one doing something wrong as well.

**Comment by 11bit** [comment]
Hmm, I've never seen this issue. Will try to replicate it. Is it browser dependent?

**Comment by 4ortytwo** [comment]
@11bit Thank you a lot for replying! I've had it happen in Firefox, though, users report it everywhere. Mobile and desktop, both Firefox and Chromium.

**Comment by 11bit** [comment]
@4ortytwo I tried to leave demo app for a couple of days in FF and Chrome but haven't seen the bug. 
1. Do you know any additional details to how to reproduce the bug more reliably? 
2. Maybe you have a stacktrace? 
3. How does the bug manifest itself? App stops working?

**Comment by 4ortytwo** [comment]
@11bit I may have found the cause, not entirely sure. I was using Next PWA (@ducanh2912/next-pwa). 
Trying to test it without the package now. 

I may be getting beyond the scope of this issue 🙏 What would be the best way to use Jotai MiniDB with next js?

**Comment by 11bit** [comment]
> I may be getting beyond the scope of this issue 🙏 What would be the best way to use Jotai MiniDB with next js?

Sure, what particular question do you have?

**Comment by 11bit** [comment]
I am closing this issue for now. Feel free to reopen if needed.
