### ISSUE TITLE
Question: how to get db.item TS type?

### ISSUE THREAD

**Issue by yiluzhang** [11bit/jotai-minidb#9]
like: 
```typescript
const code: string = useAtomValue(db.item('code'));
```

**Comment by 11bit** [comment]
You can define type when you create an instance of database:

```
const db = new MiniDb<string>();

const code = useAtomValue(db.item('code')); // Will be a string
```

**Comment by yiluzhang** [comment]
> You can define type when you create an instance of database:
> 
> ```
> const db = new MiniDb<string>();
> 
> const code = useAtomValue(db.item('code')); // Will be a string
> ```

I want to save some multi data of the current user in the one db, such as contacts, books, articles.
How to get item and type?
```typescript
const books = useAtomValue(…);
// book [{ title: 'Cook book', author: 'Sam', introduction: 'some text' }]
```

**Comment by 11bit** [comment]
Something like this:

```tsx
type Book = {
  title: string,
  author: string
}
type Articles = {
  name: string,
}

const books = new MiniDb<Book>({
   name: 'books'
});
const articles = new MiniDb<Article>({
  name: 'articles'
})

const books = useAtomValue(…);
const articles = useAtomValue(…);
```

**Comment by yiluzhang** [comment]
> Something like this:
> 
> ```tsx
> type Book = {
>   title: string,
>   author: string
> }
> type Articles = {
>   name: string,
> }
> 
> const books = new MiniDb<Book>({
>    name: 'books'
> });
> const articles = new MiniDb<Article>({
>   name: 'articles'
> })
> 
> const books = useAtomValue(…);
> const articles = useAtomValue(…);
> ```

I tried db.item and I can get item data, but the type seems wrong. I put multiple data in one db in the hope that it will be easier to clean up.

**Comment by 11bit** [comment]
It is designed to be one db per data type. If you want to store different data in the same db you will probably need to typecast it yourself every time:

```tsx
const db = new MiniDb()

const book = useAtomValue((db as MiniDb<Books>).item('book-1'));
const articles = useAtomValue((db as MiniDb<Articles>).item('article-1'));
```

**Comment by yiluzhang** [comment]
>被设计为每个数据类型一个数据库。如果您想在同一数据库中存储不同的数据，您可能需要每次都自己进行类型广播：>> ```tsx> const db = 新 MiniDb()>> const book = useAtomValue((db as MiniDb<Books>).item('book-1'));> const articles = useAtomValue((db as MiniDb<Articles>).item('article-1'));> ```


> 它被设计为每个数据类型一个数据库。如果您想在同一数据库中存储不同的数据，您可能需要每次都自己进行类型广播：
> 
> ```tsx
> const db = new MiniDb()
> 
> const book = useAtomValue((db as MiniDb<Books>).item('book-1'));
> const articles = useAtomValue((db as MiniDb<Articles>).item('article-1'));
> ```

thanks
